### ISSUE TITLE
cannot create ticket in the hive

### ISSUE THREAD

**Issue by marianoka** [weslambert/securityonion-n8n#1]
When testing connection between n8n and the hive I get this msg:
N8n points to https://localhost/thehive

{"name":"RequestError","message":"Error: connect ECONNREFUSED 127.0.0.1:443","cause":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":443},"error":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":443},"options":{"timeout":300000,"headers":{"Authorization":"Bearer NyuN/VzA4KJr0HgLX9BTc+OWa11eyGNc"},"method":"POST","uri":"https://localhost/thehive/api/alert","body":{"title":"test","description":"test","severity":2,"date":null,"tags":["test"],"tlp":2,"status":"New","type":"test","source":"test","sourceRef":"test","follow":true},"rejectUnauthorized":true,"json":true,"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}

**Comment by weslambert** [comment]
Keep in mind that n8n's perception of `localhost` is local to the scope of the n8n container. Instead, try using the IP address of the host for your request.

**Comment by marianoka** [comment]
![thehive](https://user-images.githubusercontent.com/9213379/117433946-72750880-af02-11eb-99c1-cdbf5c54a384.jpg)
Ok! I have tried that but I get certifcate error despite I tick "ignor ssl issues" checkox.

UPDATE - Get no error but not ticket. Empty response
![Screenshot 2021-05-07 at 07-58-52 n8n - ▶️](https://user-images.githubusercontent.com/9213379/117440290-3f367780-af0a-11eb-9ec0-78474d03ca89.png)
