### ISSUE TITLE
Update n8n to latest version

### ISSUE THREAD

**Issue by john-mathew-itt** [weslambert/securityonion-n8n#2]
Hi Wes,

Would this image be updated to the latest version? I use a lot of your work in my profession, so I really appreciate it.

Regards,
John Mathew.

**Comment by weslambert** [comment]
I'll take a look. It's a been a minute since I've had the opportunity to review several projects, honestly. 😅   Thanks for your support!

**Comment by weslambert** [comment]
Are you able to test using the wlambert/n8n-test image?

**Comment by john-mathew-itt** [comment]
Yes @weslambert, the image works fine. Pretty psyched to see all the neat new features. Thanks

**Comment by weslambert** [comment]
The image has been pushed to wlambert/n8n
